backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pengaturan"
    label: "Pengaturan Website"
    files:
      - label: "Pengumuman Sekolah"
        name: "pengumuman"
        file: "data.json"
        fields:
          - {label: "Judul Pengumuman", name: "judul", widget: "string"}
          - {label: "Isi Pengumuman", name: "isi", widget: "text"}